name: project_env
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
dependencies:
  - python=3.7
  - pip=19.0.*
  - pip:
    #- '--editable=.' #this is for packages specified in setup.py
    - jupyter
    - matplotlib
    - seaborn
    - scikit-learn
    - numpy
    - scipy
    - pandas
    - networkx
    - powerlaw    
    - random
    - math
    - collections    
